---
- hosts: gluster_servers
  vars_prompt:
    - name: replicacount
      prompt: Replica Count? (2/3)
      private: no
  tasks:
    - name: Add GlusterFS repo GPO key through shell
      shell: wget -O - http://download.gluster.org/pub/gluster/glusterfs/3.9/rsa.pub | apt-key add -
      args:
        warn: False
    - name: Add GlusterFS repository
      apt_repository:
        repo='deb http://download.gluster.org/pub/gluster/glusterfs/3.9/LATEST/Debian/jessie/apt jessie main'
        state=present
        filename=gluster-fs
    - name: Install GlusterFS
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - glusterfs-*
    - name: Ensure GlusterFS service is running
      service:
        name=glusterfs-*
        state=started
    - name: Create GlusterFS brick
      file:
        path=/srv/glusterfs/brick
        state=directory
    - name: Create GlusterFS volume
      gluster_volume:
        bricks=/srv/glusterfs/brick
        cluster={{groups.gluster_servers | join(",")}}
        replicas={{replicacount}}
        name=wwwhtml
        state=present
        force=true
      run_once: true
    - name: Start GlusterFS volume
      gluster_volume:
        name=wwwhtml
        state=started
    - name: Create GlusterFS brick mount dir
      file:
        path=/var/www/html
        state=directory
    - name: Mount
      mount:
        name: /var/www/html
        src: 127.0.0.1:/wwwhtml
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted
    - name: Install NginX
      apt:
        name: nginx 
        state: present
    - name: Reload NginX
      service:
        name=nginx
        state=reloaded
