---
- hosts: gluster_servers
  vars_prompt:
    - name: replicacount
      prompt: Replica Count? (2/3)
      private: no
    - name: gfsbrickpath
      prompt: Brick dir? (e.g. /data/brick1)
      private: no
    - name: gfsbrickname
      prompt: Brick name?
      private: no
    - name: gfsmountdir
      prompt: Mount dir? (e.g. /data/app)
      private: no
  tasks:
    - name: Add GlusterFS repo GPO key through shell
      shell: wget -O - http://download.gluster.org/pub/gluster/glusterfs/3.9/rsa.pub | apt-key add -
      args:
        warn: False
    - name: Add GlusterFS repository
      apt_repository:
        repo='deb http://download.gluster.org/pub/gluster/glusterfs/3.9/LATEST/Debian/jessie/apt jessie main'
        state=present
        filename=gluster-fs
    - name: Install GlusterFS
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - glusterfs-*
    - name: Ensure GlusterFS service is running
      service:
        name=glusterfs-*
        state=started
    - name: Create GlusterFS brick
      file:
        path={{gfsbrickpath}}
        state=directory
    - name: Create GlusterFS volume
      gluster_volume:
        bricks={{gfsbrickpath}}
        cluster={{groups.gluster_servers | join(",")}}
        replicas={{replicacount}}
        name={{gfsbrickname}}
        state=present
        force=true
      run_once: true
    - name: Start GlusterFS volume
      gluster_volume:
        name={{gfsbrickname}}
        state=started
    - name: Create GlusterFS brick mount dir
      file:
        path={{gfsmountdir}}
        state=directory
    - name: Mount
      mount:
        name: {{gfsmountdir}}
        src: 127.0.0.1:/{{gfsbrickname}}
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted
